// Generated by gencpp from file canalystii_msg/can.msg
// DO NOT EDIT!


#ifndef CANALYSTII_MSG_MESSAGE_CAN_H
#define CANALYSTII_MSG_MESSAGE_CAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace canalystii_msg
{
template <class ContainerAllocator>
struct can_
{
  typedef can_<ContainerAllocator> Type;

  can_()
    : header()
    , id(0)
    , timeflag(0)
    , sendtype(0)
    , remoteflag(0)
    , externflag(0)
    , datalen(0)
    , data()  {
      data.assign(0);
  }
  can_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , timeflag(0)
    , sendtype(0)
    , remoteflag(0)
    , externflag(0)
    , datalen(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint32_t _timeflag_type;
  _timeflag_type timeflag;

   typedef uint8_t _sendtype_type;
  _sendtype_type sendtype;

   typedef uint8_t _remoteflag_type;
  _remoteflag_type remoteflag;

   typedef uint8_t _externflag_type;
  _externflag_type externflag;

   typedef uint8_t _datalen_type;
  _datalen_type datalen;

   typedef boost::array<uint8_t, 8>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::canalystii_msg::can_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::canalystii_msg::can_<ContainerAllocator> const> ConstPtr;

}; // struct can_

typedef ::canalystii_msg::can_<std::allocator<void> > can;

typedef boost::shared_ptr< ::canalystii_msg::can > canPtr;
typedef boost::shared_ptr< ::canalystii_msg::can const> canConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::canalystii_msg::can_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::canalystii_msg::can_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace canalystii_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'canalystii_msg': ['/home/me/catkin_exo/src/canalystii_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::canalystii_msg::can_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canalystii_msg::can_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canalystii_msg::can_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canalystii_msg::can_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canalystii_msg::can_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canalystii_msg::can_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::canalystii_msg::can_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e974a5e243febe68ac8618d673926338";
  }

  static const char* value(const ::canalystii_msg::can_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe974a5e243febe68ULL;
  static const uint64_t static_value2 = 0xac8618d673926338ULL;
};

template<class ContainerAllocator>
struct DataType< ::canalystii_msg::can_<ContainerAllocator> >
{
  static const char* value()
  {
    return "canalystii_msg/can";
  }

  static const char* value(const ::canalystii_msg::can_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::canalystii_msg::can_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 id\n\
uint32 timeflag\n\
uint8 sendtype\n\
uint8 remoteflag\n\
uint8 externflag\n\
uint8 datalen\n\
uint8[8] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::canalystii_msg::can_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::canalystii_msg::can_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.timeflag);
      stream.next(m.sendtype);
      stream.next(m.remoteflag);
      stream.next(m.externflag);
      stream.next(m.datalen);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct can_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::canalystii_msg::can_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::canalystii_msg::can_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "timeflag: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeflag);
    s << indent << "sendtype: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sendtype);
    s << indent << "remoteflag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remoteflag);
    s << indent << "externflag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.externflag);
    s << indent << "datalen: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.datalen);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANALYSTII_MSG_MESSAGE_CAN_H
